Document: tux-frontend
Title: Debian tux-frontend Manual
Author: <insert document author here>
Abstract: This manual describes what tux-frontend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tux-frontend/tux-frontend.sgml.gz

Format: postscript
Files: /usr/share/doc/tux-frontend/tux-frontend.ps.gz

Format: text
Files: /usr/share/doc/tux-frontend/tux-frontend.text.gz

Format: HTML
Index: /usr/share/doc/tux-frontend/html/index.html
Files: /usr/share/doc/tux-frontend/html/*.html
